"""Regenerate the demo page's sample documents from the frozen corpus.

The samples are committed rather than fetched so the demo page needs no build
step and no network beyond its own origin. Run this whenever the frozen corpus
is regenerated, so the header in samples.js stays true.

    PYTHONPATH=. .venv/bin/python tools/make_samples.py
"""

from __future__ import annotations

import json
import sys
from pathlib import Path

CORPUS = Path("data/corpus/frozen/documents.jsonl")
OUTPUT = Path("app/web/static/samples.js")
MAX_CHARS = 1100

#: Template id -> the label shown on the demo button. Chosen to span the range
#: of servicing artefacts: a free-text note, a numeric statement, a regulatory
#: response and a dated log.
WANTED = {
    "call_center_note": "Call centre note",
    "payoff_demand": "Payoff demand statement",
    "notice_of_error_response": "RESPA notice of error response",
    "collection_call_log": "Collection contact log",
}


def main() -> int:
    picked: dict[str, str] = {}
    for line in CORPUS.open(encoding="utf-8"):
        doc = json.loads(line)
        template = doc["template_id"]
        if template in WANTED and template not in picked and len(doc["text"]) <= MAX_CHARS:
            picked[template] = doc["text"]

    missing = set(WANTED) - set(picked)
    if missing:
        print(f"no suitable document for {sorted(missing)}", file=sys.stderr)
        return 1

    samples = [{"label": WANTED[t], "text": picked[t]} for t in WANTED]
    OUTPUT.write_text(
        "// Generated by tools/make_samples.py from data/corpus/frozen.\n"
        "// Committed so the demo page needs no build step and no network\n"
        "// beyond its own origin.\n"
        "window.SAMPLES = " + json.dumps(samples, indent=2, ensure_ascii=False) + ";\n",
        encoding="utf-8",
    )
    print(f"wrote {len(samples)} samples to {OUTPUT}")
    for sample in samples:
        print(f"  {sample['label']:<34} {len(sample['text'])} chars")
    return 0


if __name__ == "__main__":
    sys.exit(main())
